# Generated by Django 5.2.3 on 2025-06-20 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tipo do produto: Aéreo, Hotel, etc', max_length=100, unique=True, verbose_name='Nome do Índice')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Catalogs - Índice de Reajuste',
                'verbose_name_plural': 'Catalogs - Índices de Reajuste',
            },
        ),
        migrations.CreateModel(
            name='BillingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_date', models.DateField(unique=True, verbose_name='Ciclo')),
            ],
            options={
                'verbose_name': 'Catalogs - Calendário de Faturamento',
                'verbose_name_plural': 'Catalogs - Calendários de Faturamento',
            },
        ),
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveSmallIntegerField(unique=True, verbose_name='Quantidade de dias')),
            ],
            options={
                'verbose_name': 'Catalogs - Ciclo de Cobrança',
                'verbose_name_plural': 'Catalogs - Ciclos de Cobrança',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=100, unique=True, verbose_name='Forma de Pagamento')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Catalogs - Forma de Pagamento',
                'verbose_name_plural': 'Catalogs - Formas de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(help_text='Tipo do produto: Aéreo, Hotel, etc', max_length=100, unique=True, verbose_name='Produto')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Catalogs - Produto',
                'verbose_name_plural': 'Catalogs - Produtos',
            },
        ),
        migrations.CreateModel(
            name='ContractData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature_date', models.DateField(verbose_name='Data de Assinatura')),
                ('expiration_date', models.DateField(verbose_name='Data de Expiração')),
                ('adjustment_date', models.DateField(verbose_name='Data de Reajuste')),
                ('adjustment_index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.adjustmentindex', verbose_name='Índices para Reajuste')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Dados Contratuais',
                'verbose_name_plural': 'Dados Contratuais',
            },
        ),
        migrations.CreateModel(
            name='InvoiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creation_type', models.CharField(choices=[('BY_CLIENT', 'Por Cliente'), ('BY_GROUP', 'Por Grupo')], max_length=20, verbose_name='Criação da Fatura')),
                ('has_cutoff', models.BooleanField(verbose_name='Possui data de corte?')),
                ('cutoff_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dias de corte')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='companies.company', verbose_name='Empresa')),
                ('payment_methods', models.ManyToManyField(to='financial.paymentmethod', verbose_name='Forma de Pagamento')),
            ],
            options={
                'verbose_name': 'Configuração de Fatura',
                'verbose_name_plural': 'Configurações de Fatura',
            },
        ),
        migrations.CreateModel(
            name='FeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('send_report', models.BooleanField(verbose_name='Enviar Relatório')),
                ('term_date', models.DateField(verbose_name='Prazo')),
                ('fee_closing_date', models.DateField(verbose_name='Fechamento do FEE')),
                ('fee_report', models.BooleanField(verbose_name='Relatório do FEE')),
                ('fee_invoice', models.BooleanField(verbose_name='Fatura do FEE')),
                ('validation', models.CharField(max_length=50, verbose_name='Validação')),
                ('cutoff_date', models.DateField(verbose_name='Data de Corte')),
                ('dispatch_date', models.DateField(verbose_name='Data de Envio')),
                ('payment_date', models.DateField(verbose_name='Dia do Pagamento')),
                ('has_invoice_report', models.BooleanField(verbose_name='NF do Relatório')),
                ('cancelation_fee', models.BooleanField(verbose_name='Cobrar taxa de cancelamento')),
                ('include_du_fee', models.BooleanField(verbose_name='Incluir Taxa DU')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='companies.company', verbose_name='Empresa')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.billingcycle', verbose_name='Ciclo')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.paymentmethod', verbose_name='Forma de Pagamento')),
            ],
            options={
                'verbose_name': 'Detalhes do FEE',
                'verbose_name_plural': 'Detalhes do FEE',
            },
        ),
        migrations.CreateModel(
            name='FeeBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_type', models.CharField(max_length=100, verbose_name='Tipo de cobrança')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='companies.company', verbose_name='Empresa')),
                ('products_to_charge', models.ManyToManyField(to='financial.product', verbose_name='Quais produtos cobrar o FEE')),
            ],
            options={
                'verbose_name': 'Faturamento FEE',
                'verbose_name_plural': 'Faturamentos FEE',
            },
        ),
        migrations.CreateModel(
            name='BillingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term_days', models.PositiveSmallIntegerField(verbose_name='Prazo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.billingcalendar', verbose_name='Calendário')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='companies.company', verbose_name='Empresa')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.billingcycle', verbose_name='Ciclo')),
                ('products_to_bill', models.ManyToManyField(to='financial.product', verbose_name='Produtos a Faturar')),
            ],
            options={
                'verbose_name': 'Política de Faturamento',
                'verbose_name_plural': 'Políticas de Faturamento',
            },
        ),
    ]
