# Generated by Django 5.2.3 on 2025-06-17 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome jurídico oficial', max_length=255, verbose_name='Razão Social')),
                ('fantasy_name', models.CharField(help_text='Nome utilizado comercialmente', max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(help_text='Validação obrigatória', max_length=14, verbose_name='CNPJ')),
                ('full_address', models.TextField(blank=True, help_text='Utilizado para referência e notas fiscais', null=True, verbose_name='Endereço Completo')),
                ('segment', models.CharField(help_text='Ex: Saúde, Educação, Indústria', max_length=255, verbose_name='Segmento')),
                ('benner_code', models.CharField(help_text='Código cadastrado no sistema Benner', max_length=255, verbose_name='Código Interno (Benner)')),
                ('obt_link', models.CharField(help_text='Endereço da Argo ou outro OBT', max_length=255, verbose_name='Link do OBT')),
                ('website', models.CharField(blank=True, help_text='Página institucional', max_length=255, null=True, verbose_name='Site')),
                ('travel_manager_name', models.CharField(help_text='Contato principal e backups', max_length=255, verbose_name='Nome do Gestor de Viagem')),
                ('travel_manager_email', models.EmailField(help_text='Contato principal e backups', max_length=255, verbose_name='Email do Gestor de Viagem')),
                ('management_phone', models.CharField(help_text='Telefone fixo', max_length=255, verbose_name='Telefone Fixo da Gestão')),
                ('management_mobile_phone', models.CharField(help_text='Telefone móvel', max_length=255, verbose_name='Telefone Móvel da Gestão')),
                ('account_executive', models.CharField(help_text='Representante da agência', max_length=255, verbose_name='Executivo de Contas')),
                ('observations', models.TextField(blank=True, help_text='Regras específicas por cliente', null=True, verbose_name='Observações/Particularidades')),
            ],
            options={
                'verbose_name': 'Companhia',
                'verbose_name_plural': 'Companhias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VipSecretaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('company_name', models.CharField(max_length=255, verbose_name='Empresa')),
                ('secretary_allocation', models.CharField(max_length=255, verbose_name='Alocação Secretária')),
                ('executives_served', models.CharField(max_length=255, verbose_name='Excutivos atendidos')),
                ('public_tower', models.TextField(verbose_name='Torre / Público')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'VIP Secretaria',
                'verbose_name_plural': 'VIP Secretarias',
                'ordering': ['name'],
            },
        ),
    ]
