# Generated by Django 5.2.3 on 2025-06-18 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome jurídico oficial', max_length=255, verbose_name='Razão Social')),
                ('fantasy_name', models.CharField(help_text='Nome utilizado comercialmente', max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(help_text='Validação obrigatória', max_length=14, verbose_name='CNPJ')),
                ('full_address', models.TextField(blank=True, help_text='Utilizado para referência e notas fiscais', null=True, verbose_name='Endereço Completo')),
                ('segment', models.CharField(help_text='Ex: Saúde, Educação, Indústria', max_length=255, verbose_name='Segmento')),
                ('benner_code', models.CharField(help_text='Código cadastrado no sistema Benner', max_length=255, verbose_name='Código Interno (Benner)')),
                ('obt_link', models.CharField(help_text='Endereço da Argo ou outro OBT', max_length=255, verbose_name='Link do OBT')),
                ('website', models.CharField(blank=True, help_text='Página institucional', max_length=255, null=True, verbose_name='Site')),
                ('notes', models.TextField(blank=True, help_text='Regras específicas por cliente', null=True, verbose_name='Observações/Particularidades')),
            ],
            options={
                'verbose_name': 'Companhia',
                'verbose_name_plural': 'Companhias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('role', models.CharField(max_length=100, verbose_name='Cargo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone Fixo')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='Celular')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('is_travel_manager', models.BooleanField(default=False, verbose_name='Gestor de Viagem')),
                ('is_account_executive', models.BooleanField(default=False, verbose_name='Executivo de Contas')),
                ('is_billing_contact', models.BooleanField(default=False, verbose_name='Contato para Cobrança')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Contato da Empresa',
                'verbose_name_plural': 'Contatos das Empresas',
            },
        ),
        migrations.CreateModel(
            name='FeeDispatchContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='companies.company', verbose_name='Empresa')),
                ('invoice_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_dispatches', to='companies.companycontact', verbose_name='Emitir NF para')),
            ],
            options={
                'verbose_name': 'Contato para Envio do FEE',
                'verbose_name_plural': 'Contatos para Envio do FEE',
            },
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_requester', models.BooleanField(default=False, verbose_name='Solicitante')),
                ('is_traveler', models.BooleanField(default=False, verbose_name='Viajante')),
                ('is_secretary', models.BooleanField(default=False, verbose_name='Secretária')),
                ('company_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companycontact', verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'VIP',
                'verbose_name_plural': 'VIPs',
                'ordering': ['company_contact__name'],
            },
        ),
    ]
