# Generated by Django 5.2.3 on 2025-06-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_live', models.DateField(verbose_name='Go Live')),
                ('name', models.CharField(help_text='Nome jurídico oficial', max_length=255, unique=True, verbose_name='Razão Social')),
                ('fantasy_name', models.CharField(help_text='Nome utilizado comercialmente', max_length=255, unique=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(help_text='Validação obrigatória', max_length=14, unique=True, verbose_name='CNPJ')),
                ('full_address', models.TextField(blank=True, help_text='Utilizado para referência e notas fiscais', null=True, verbose_name='Endereço Completo')),
                ('segment', models.CharField(help_text='Ex: Saúde, Educação, Indústria', max_length=255, verbose_name='Segmento')),
                ('benner_code', models.CharField(help_text='Código cadastrado no sistema Benner', max_length=255, verbose_name='Código Interno (Benner)')),
                ('obt_link', models.CharField(help_text='Endereço da Argo ou outro OBT', max_length=255, verbose_name='Link do OBT')),
                ('website', models.CharField(blank=True, help_text='Página institucional', max_length=255, null=True, verbose_name='Site')),
                ('notes', models.TextField(blank=True, help_text='Regras específicas por cliente', null=True, verbose_name='Observações/Particularidades')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('role', models.CharField(max_length=100, verbose_name='Cargo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone Fixo')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='Celular')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('is_travel_manager', models.BooleanField(default=False, verbose_name='Gestor de Viagem')),
                ('is_billing_contact', models.BooleanField(default=False, verbose_name='Contato para Cobrança')),
                ('is_financial_contact', models.BooleanField(default=False, verbose_name='Contato Financeiro')),
                ('is_commercial_contact', models.BooleanField(default=False, verbose_name='Contato Comercial')),
            ],
            options={
                'verbose_name': 'Contato da Empresa',
                'verbose_name_plural': 'Contatos das Empresas',
            },
        ),
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Grupo')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Grupo da Empresa',
                'verbose_name_plural': 'Grupos das Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeDispatchContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contato para Envio do FEE',
                'verbose_name_plural': 'Contatos para Envio do FEE',
            },
        ),
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ponto de venda', max_length=255, verbose_name='Ponto de Venda')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Catalogs - Ponto de Venda',
                'verbose_name_plural': 'Catalogs - Pontos de Venda',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_requester', models.BooleanField(default=False, verbose_name='Solicitante')),
                ('is_traveler', models.BooleanField(default=False, verbose_name='Viajante')),
                ('is_secretary', models.BooleanField(default=False, verbose_name='Secretária')),
            ],
            options={
                'verbose_name': 'VIP',
                'verbose_name_plural': 'VIPs',
                'ordering': ['company_contact__name'],
            },
        ),
    ]
