# Generated by Django 5.2.3 on 2025-06-18 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedispatchcontact',
            name='invoice_to',
            field=models.ForeignKey(help_text='Deve ser um Contato para Cobrança. Cadastre um usuário com este perfil em Contato da Empresa', on_delete=django.db.models.deletion.PROTECT, related_name='fee_dispatches', to='companies.companycontact', verbose_name='Emitir NF para'),
        ),
    ]
