# Generated by Django 5.2.3 on 2025-06-25 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='current_contract',
            field=models.OneToOneField(blank=True, help_text='Contrato vigente da empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_company', to='financial.contractdata', verbose_name='Contrato vigente'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='company',
            name='account_executive',
            field=models.OneToOneField(blank=True, help_text='Executivo de Contas da empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_for_company', to='companies.companycontact', verbose_name='Executivo de Contas'),
        ),
        migrations.AddField(
            model_name='companygroup',
            name='main_company',
            field=models.OneToOneField(blank=True, help_text='Empresa principal do grupo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_main_company_of', to='companies.company', verbose_name='Empresa Principal'),
        ),
        migrations.AddField(
            model_name='company',
            name='group',
            field=models.ForeignKey(help_text='Grupo ao qual esta empresa pertence', on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='companies.companygroup', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='feedispatchcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='feedispatchcontact',
            name='invoice_to',
            field=models.ForeignKey(help_text='Deve ser um Contato para Cobrança. Cadastre um usuário com este perfil em Contato da Empresa', on_delete=django.db.models.deletion.PROTECT, related_name='fee_dispatches', to='companies.companycontact', verbose_name='Emitir NF para'),
        ),
        migrations.AddField(
            model_name='company',
            name='point_of_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='point', to='companies.pointofsale', verbose_name='Ponto de Venda'),
        ),
        migrations.AddField(
            model_name='vip',
            name='company_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vips', to='companies.companycontact', verbose_name='Contato'),
        ),
    ]
